DELETE FROM genre;
INSERT INTO genre (genreid, genre) VALUES ('Fan', 'Fantasy');
INSERT INTO genre (genreid, genre) VALUES ('Adv', 'Adventure');
INSERT INTO genre (genreid, genre) VALUES ('Rom', 'Romance');
INSERT INTO genre (genreid, genre) VALUES ('Con', 'Contemporary');
INSERT INTO genre (genreid, genre) VALUES ('Dys', 'Dystopian');
INSERT INTO genre (genreid, genre) VALUES ('Mys', 'Mystery');
INSERT INTO genre (genreid, genre) VALUES ('Hor', 'Horror');
INSERT INTO genre (genreid, genre) VALUES ('Thr', 'Thriller');
INSERT INTO genre (genreid, genre) VALUES ('Par', 'Paranormal');
INSERT INTO genre (genreid, genre) VALUES ('His', 'History');
INSERT INTO genre (genreid, genre) VALUES ('Sci', 'Science Fiction');
INSERT INTO genre (genreid, genre) VALUES ('Mem', 'Memoir');
INSERT INTO genre (genreid, genre) VALUES ('Coo', 'Cooking');
INSERT INTO genre (genreid, genre) VALUES ('Art', 'Art');
INSERT INTO genre (genreid, genre) VALUES ('Sel', 'Self-help / Personal');
INSERT INTO genre (genreid, genre) VALUES ('Dev', 'Development');
INSERT INTO genre (genreid, genre) VALUES ('Mot', 'Motivational');
INSERT INTO genre (genreid, genre) VALUES ('Hea', 'Health');
INSERT INTO genre (genreid, genre) VALUES ('Tra', 'Travel');
INSERT INTO genre (genreid, genre) VALUES ('Gui', 'Guide / How-to');
INSERT INTO genre (genreid, genre) VALUES ('Fam', 'Families & Relationships');
INSERT INTO genre (genreid, genre) VALUES ('Hum', 'Humor');
INSERT INTO genre (genreid, genre) VALUES ('Chi', 'Children’');
